// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/rank.proto

package rank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  string                 `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankRequest) Reset() {
	*x = RankRequest{}
	mi := &file_proto_rank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankRequest) ProtoMessage() {}

func (x *RankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankRequest.ProtoReflect.Descriptor instead.
func (*RankRequest) Descriptor() ([]byte, []int) {
	return file_proto_rank_proto_rawDescGZIP(), []int{0}
}

func (x *RankRequest) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

type RankReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankReply) Reset() {
	*x = RankReply{}
	mi := &file_proto_rank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankReply) ProtoMessage() {}

func (x *RankReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankReply.ProtoReflect.Descriptor instead.
func (*RankReply) Descriptor() ([]byte, []int) {
	return file_proto_rank_proto_rawDescGZIP(), []int{1}
}

func (x *RankReply) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Login              string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	TotalContributions uint32                 `protobuf:"varint,3,opt,name=totalContributions,proto3" json:"totalContributions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_rank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_rank_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetTotalContributions() uint32 {
	if x != nil {
		return x.TotalContributions
	}
	return 0
}

var File_proto_rank_proto protoreflect.FileDescriptor

const file_proto_rank_proto_rawDesc = "" +
	"\n" +
	"\x10proto/rank.proto\"1\n" +
	"\vRankRequest\x12\"\n" +
	"\forganization\x18\x01 \x01(\tR\forganization\"(\n" +
	"\tRankReply\x12\x1b\n" +
	"\x05users\x18\x01 \x03(\v2\x05.UserR\x05users\"L\n" +
	"\x04User\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12.\n" +
	"\x12totalContributions\x18\x03 \x01(\rR\x12totalContributions2/\n" +
	"\x04Rank\x12'\n" +
	"\vGetRankings\x12\f.RankRequest\x1a\n" +
	".RankReplyB\x0eZ\f./proto;rankb\x06proto3"

var (
	file_proto_rank_proto_rawDescOnce sync.Once
	file_proto_rank_proto_rawDescData []byte
)

func file_proto_rank_proto_rawDescGZIP() []byte {
	file_proto_rank_proto_rawDescOnce.Do(func() {
		file_proto_rank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rank_proto_rawDesc), len(file_proto_rank_proto_rawDesc)))
	})
	return file_proto_rank_proto_rawDescData
}

var file_proto_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_rank_proto_goTypes = []any{
	(*RankRequest)(nil), // 0: RankRequest
	(*RankReply)(nil),   // 1: RankReply
	(*User)(nil),        // 2: User
}
var file_proto_rank_proto_depIdxs = []int32{
	2, // 0: RankReply.users:type_name -> User
	0, // 1: Rank.GetRankings:input_type -> RankRequest
	1, // 2: Rank.GetRankings:output_type -> RankReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_rank_proto_init() }
func file_proto_rank_proto_init() {
	if File_proto_rank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rank_proto_rawDesc), len(file_proto_rank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rank_proto_goTypes,
		DependencyIndexes: file_proto_rank_proto_depIdxs,
		MessageInfos:      file_proto_rank_proto_msgTypes,
	}.Build()
	File_proto_rank_proto = out.File
	file_proto_rank_proto_goTypes = nil
	file_proto_rank_proto_depIdxs = nil
}
